### ISSUE TITLE
Cannot run python/run_bazel.sh -- 'Linear' object does not support item assignment

### ISSUE THREAD

**Issue by vors** [amatveiakin/polykit#2]
Hi @amatveiakin !

I'm able to build the cpp folder.
I'm getting the following error when trying to use the python folder. 

```
root@7677643db062:/polykit/python# ./run_bazel.sh 
INFO: Analyzed target //python:workspace (3 packages loaded, 65 targets configured).
INFO: Found 1 target...
Target //python:workspace up-to-date:
  bazel-bin/python/workspace
INFO: Elapsed time: 16.332s, Critical Path: 0.01s
INFO: 4 processes: 4 internal.
INFO: Build completed successfully, 4 total actions
INFO: Build completed successfully, 4 total actions
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/14a528a340f6fd152f2d42938a274431/execroot/__main__/bazel-out/k8-fastbuild/bin/python/workspace.runfiles/__main__/python/workspace.py", line 5, in <module>
    expr = QLi6(1,2,3,4,5,6)
  File "/polykit/python/polypy/lib/polylog_qli.py", line 149, in QLi6
    def QLi6(*points): return QLi(6, args_to_iterable(points))
  File "/polykit/python/polypy/lib/polylog_qli.py", line 142, in QLi
    return qli_impl(weight, tagged_points)
  File "/polykit/python/polypy/lib/polylog_qli.py", line 133, in qli_impl
    ret = symbol_product(cross_ratio([p[0] for p in points]), qli_impl(weight - 1, points))
  File "/polykit/python/polypy/lib/polylog_qli.py", line 133, in qli_impl
    ret = symbol_product(cross_ratio([p[0] for p in points]), qli_impl(weight - 1, points))
  File "/polykit/python/polypy/lib/polylog_qli.py", line 133, in qli_impl
    ret = symbol_product(cross_ratio([p[0] for p in points]), qli_impl(weight - 1, points))
  [Previous line repeated 1 more time]
  File "/polykit/python/polypy/lib/polylog_qli.py", line 131, in qli_impl
    return subsums()
  File "/polykit/python/polypy/lib/polylog_qli.py", line 125, in subsums
    ret += symbol_product(qli_node_func(points[i:i+4]), qli_impl(weight - 1, foundation))
  File "/polykit/python/polypy/lib/delta.py", line 55, in symbol_product
    return tensor_product(*multipliers, product=lambda a, b: a + b)
  File "/polykit/python/polypy/lib/linear.py", line 142, in tensor_product
    return functools.reduce(
  File "/polykit/python/polypy/lib/linear.py", line 143, in <lambda>
    lambda lhs, rhs: _tensor_product_two(lhs, rhs, product),
  File "/polykit/python/polypy/lib/linear.py", line 135, in _tensor_product_two
    ret[obj] = coeff_l * coeff_r
TypeError: 'Linear' object does not support item assignment
```

**Comment by amatveiakin** [comment]
Thanks! It appears I haven't checked the pure Python version for a looong time :)
Fixed now.
